"""Firts

Revision ID: 7ac371592375
Revises: 9d90c1402e0f
Create Date: 2022-09-15 20:00:14.826995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac371592375'
down_revision = '9d90c1402e0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'item', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='unique')
    # ### end Alembic commands ###
